name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the ubuntu-common Docker image
      run: docker build ubuntu-common --tag xs-ubuntu-common:$(date +%s)
